//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPage.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;From: &lt;/td&gt;
        ///                        &lt;td&gt;&lt;b&gt;{0} &amp;lt;{2}&amp;gt;&lt;/b&gt;   
        ///                    &lt;/tr&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;Email: &lt;/td&gt;
        ///                        &lt;td&gt;&lt;b&gt;{2}&lt;/b&gt;&lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;Phone: &lt;/td&gt;
        ///                        &lt;td&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/td&gt;
        ///                    &lt;/tr&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td&gt;At: &lt;/td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailContactBody {
            get {
                return ResourceManager.GetString("EmailContactBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;Message: &lt;br /&gt;&lt;br /&gt; {0}.
        /// </summary>
        public static string EmailContactMessage {
            get {
                return ResourceManager.GetString("EmailContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyPage contact from {0}.
        /// </summary>
        public static string EmailContactSubject {
            get {
                return ResourceManager.GetString("EmailContactSubject", resourceCulture);
            }
        }
    }
}
